version: 'version 3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: name
    environment:
      - MYSQL_ROOT_PASSWORD = 1234
      - MYSQL_USER = kartaca
      - MYSQL_PASSWORD = 1234
      - MYSQL_DATABASE = airflow
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  webserver:
    image: apache/airflow:2.2.3
    ports:
      - "8081:8080"
    environment:
      - AIRFLOW__WEBSERVER__SECRET_KEY = 
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN =
      - AIRFLOW__CELERY__RESULT_BACKEND =
      - AIRFLOW_CORE__LOAD_EXAMPLES = False
      - AIRFLOW__CORE__EXECUTOR = LocalExecutor
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION = False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
    depends_on:
      - mysql  
